name: Replacer
on: push
jobs:
  Replace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: '"`Ooo Animated Sticker 👀...`"'
          replace: "get_string('sts_9')"
          exclude: 'strings/'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Hurrr2'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: New-dev0
          commit_user_email: newdev0@outlook.com
          commit_author: New-dev0 <newdev0@outlook.com>
