name: Replacer
on: push

env:
  GitHubMail: "newdev0@outlook.com"
  GitHubName: "New-dev0"

jobs:
  Replace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: '"`Ooo Animated Sticker 👀...`"'
          replace: "get_string('sts_9')"
          exclude: 'strings/'
      - name: "Set Git Configs & Secrets"
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.G_TOKEN }}@github.com" > ~/.git-credentials
      - name : push stuff
        run: |
          git add .
          git commit -m "replace"
          git push
